# Generated by Django 5.0.2 on 2024-05-12 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='Pagina',
        ),
        migrations.AlterModelOptions(
            name='pagina',
            options={'verbose_name': 'Página', 'verbose_name_plural': 'Páginas'},
        ),
    ]
