# Generated by Django 5.0.2 on 2024-05-12 19:25

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0002_rename_product_pagina_alter_pagina_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagina',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Posición'),
        ),
        migrations.AlterField(
            model_name='pagina',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Descripción'),
        ),
    ]
