# Generated by Django 5.0.2 on 2024-05-31 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='changerole',
            options={'verbose_name': 'Petición Vendedor', 'verbose_name_plural': 'Peticiones Vendedores'},
        ),
    ]
