# Generated by Django 5.0.2 on 2024-05-30 12:57

import django.core.validators
import django.db.models.deletion
import django_ckeditor_5.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Tag', max_length=50, verbose_name='Nombre')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name_plural': 'Tags',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Producto', max_length=50, verbose_name='Producto')),
                ('description', models.TextField(blank=True, max_length=300, null=True, verbose_name='Descripción')),
                ('content', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Contenido')),
                ('image', models.ImageField(default='null', null=True, upload_to='productos', verbose_name='Imagen principal')),
                ('price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Precio')),
                ('ref', models.CharField(blank=True, max_length=16, null=True, unique=True, verbose_name='Referencia')),
                ('visible', models.BooleanField(default=True, verbose_name='Visible')),
                ('in_stock', models.BooleanField(default=True, verbose_name='En Stock')),
                ('stock', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(-1), django.core.validators.MaxValueValidator(10000)])),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha creación')),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Última actualización')),
                ('user', models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
                ('tags', models.ManyToManyField(blank=True, to='tiendas.tag', verbose_name='Tags')),
            ],
            options={
                'verbose_name_plural': 'Productos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail', models.TextField(blank=True, default='Detail', null=True, verbose_name='Detail')),
                ('review_content', models.TextField(blank=True, null=True, verbose_name='Contenido')),
                ('rating', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Valoración')),
                ('visible', models.BooleanField(default=True, verbose_name='Visible')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha Creación')),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Última actualización')),
                ('producto', models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.CASCADE, to='tiendas.producto', verbose_name='Producto')),
                ('user', models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name_plural': 'Reviews',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Tienda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Tienda', max_length=50, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, max_length=300, null=True, verbose_name='Descripción')),
                ('content', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Contenido')),
                ('image', models.ImageField(default='null', null=True, upload_to='tiendas', verbose_name='Imagen Principal')),
                ('web', models.CharField(blank=True, max_length=50, null=True, verbose_name='Web')),
                ('url', models.CharField(blank=True, max_length=255, null=True, verbose_name='Web URL')),
                ('email', models.EmailField(blank=True, max_length=50, null=True, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=12, null=True, verbose_name='Teléfono')),
                ('address', models.TextField(blank=True, max_length=255, null=True, verbose_name='Dirección')),
                ('visible', models.BooleanField(default=True, verbose_name='Visible')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha Creación')),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Última actualización')),
                ('tags', models.ManyToManyField(blank=True, to='tiendas.tag', verbose_name='Tags')),
                ('user', models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name_plural': 'Tiendas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='producto',
            name='tienda',
            field=models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.CASCADE, to='tiendas.tienda', verbose_name='Tienda'),
        ),
    ]
